Ability to configure global options
dpoetzsch/md-pickers pull request #12
Opened 2017-06-24 00:30 UTC by robin-thoni

Issue #11

#### Bugfixes

* Fixed error when input are not in a form (cf2b00f)
* Fixed date object error (7417a93)

#### Features

* Added service to configure settings globally
* Added demo

2017-06-28 19:36 UTC, dpoetzsch requested changes
Lovely, thanks!

I added some remarks in the code. Only little issues though.

Furthermore, it looks like all the files in demo-dist are auto-generated? If yes, we should exclude them from the repository.

Also, at some point we should merge your demo with the original one (which might be broken at the moment)... But this is work for another PR.

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpDatePicker/mdpDatePicker.js
> +                    return minDateValidator(viewValue, scope.dateFormat, minDate);
I think, here you break the possibility to change the `minDate` after creation of the picker using the scope binding. I believe we have to do a `scope.minDate || $mdpLocale.date.minDate` here (and cleanup the constant definition above).

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpDatePicker/mdpDatePicker.js
> +                    return maxDateValidator(viewValue, scope.dateFormat, maxDate);
same as with `minDate`

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpDatePicker/mdpDatePicker.js
> +                    return filterValidator(viewValue, scope.dateFormat, dateFilter);
same as with `minDate`

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpDatePicker/mdpDatePicker.js
> +                        dateFilter: dateFilter,
same as with `minDate` above (for all three lines)

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpTimePicker/mdpTimePicker.js
> +                    ampm: options.ampm == null ? $mdpLocale.time.ampm : options.ampm
I think we might go better with `angular.isDefined(options.ampm) ? options.ampm : $mdpLocale.time.ampm` here

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpTimePicker/mdpTimePicker.js
> +                return minTimeValidator(viewValue, scope.timeFormat, minTime);
same as with `minDate` in date picker

2017-06-28 19:36 UTC, dpoetzsch commented on src/components/mdpTimePicker/mdpTimePicker.js
> +                return maxTimeValidator(viewValue, scope.timeFormat, maxTime);
same as with `minDate` in date picker

2017-07-01 03:06 UTC, robin-thoni commented
> I added some remarks in the code. Only little issues though.

I fixed them

> Furthermore, it looks like all the files in demo-dist are auto-generated? If yes, we should exclude them from the repository.

I was hesitant about that before making the PR, and I ended by keeping it. Now, it is ignored.

> Also, at some point we should merge your demo with the original one (which might be broken at the moment)... But this is work for another PR.

Yes :) I spotted a few other bugs, I'll probably fix them

2017-07-03 19:07 UTC, closed without merging